apiVersion: v1
kind: Pod
metadata:
  name: flask-app-with-nginx
  labels:
    app: flask-app
    component: web
spec:
  containers:
  # Nginx proxy container (sidecar)
  - name: nginx-proxy
    image: your-registry/nginx-proxy:latest  # Built from Dockerfile.nginx
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    env:
    # Backend configuration - points to Flask container on localhost
    - name: BACKEND_HOST
      value: "localhost"
    - name: BACKEND_PORT
      value: "8080"
    # Nginx configuration
    - name: NGINX_PORT
      value: "80"
    - name: NGINX_WORKER_PROCESSES
      value: "auto"
    - name: NGINX_WORKER_CONNECTIONS
      value: "1024"
    # Proxy timeouts
    - name: PROXY_READ_TIMEOUT
      value: "60s"
    - name: PROXY_CONNECT_TIMEOUT
      value: "60s"
    - name: PROXY_SEND_TIMEOUT
      value: "60s"
    # Client settings
    - name: CLIENT_MAX_BODY_SIZE
      value: "10m"
    - name: KEEPALIVE_TIMEOUT
      value: "65s"
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "250m"
    livenessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /health
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 2
    securityContext:
      runAsNonRoot: true
      runAsUser: 101  # nginx user
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false  # nginx needs to write to cache dirs
  
  # Flask application container
  - name: flask-app
    image: your-registry/flask-app:latest  # Your Flask app image
    ports:
    - name: flask
      containerPort: 8080
      protocol: TCP
    env:
    - name: FLASK_ENV
      value: "production"
    - name: PORT
      value: "8080"
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /status  # Your Flask app health endpoint
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
      timeoutSeconds: 3
      failureThreshold: 3
    readinessProbe:
      httpGet:
        path: /status
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
      failureThreshold: 2
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    volumeMounts:
    - name: tmp
      mountPath: /tmp
  
  volumes:
  - name: tmp
    emptyDir: {}
  
  restartPolicy: Always
  
  # Security context for the entire pod
  securityContext:
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

---
# Service to expose the pod
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    app: flask-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: flask-app
    component: web
